### ISSUE TITLE
Is there a level 9?

### ISSUE THREAD

**Issue by KellyWay** [hgarc014/git-game#33]
Level 8 led me to level 10

**Comment by KellyWay** [comment]
I was doing it wrong

**Comment by skydvr** [comment]
I wish you were clearer about what you did wrong, because I noticed the same thing.  Not sure what I'm doing wrong.  Level 8 compares the differences in the remember file, which points me to another branch, which then says "Level 10".  I never get anything that says "Level 9".  Oh well - not going to stress over it, although I did re-do the whole game just to make sure that I really didn't see a level 9.... :-)
